CarSimulator.Server/Models/Car.cs
using DataLogicLibrary.Infrastructure.Enums;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarSimulator.Server.Models
{
    public class Car
    {
        public CardinalDirection CardinalDirection { get; set; }
        public int GasValue { get; set; }

    }
}

CarSimulator.Server/Models/Driver.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CarSimulator.Server.Models
{
    public class Driver
    {
        public string Title { get; set; }
        public string First { get; set; }
        public string Last { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
    }
}

CarSimulator.Server/Models/ViewModels/SimulationViewModel.cs
using CarSimulator.Server.Models;
using DataLogicLibrary.DTO;

namespace CarSimulator.Server.Models.ViewModels
{
    public class SimulationViewModel
    {

        public bool IsRunning { get; set; } = false;

        public int SelectedAction { get; set; }

        public Car Car { get; set; }

        public Driver Driver { get; set; }

        public StatusDTO CurrentStatus { get; set; }

        public string CarStatusMessage { get; set; }

        public string DriverStatusMessage { get; set; }

        public string CurrentActionMessage { get; set; }



    }
}

CarSimulator.Server/Controllers/CarSimulatorController.cs
using APIServiceLibrary.Services;
using CarSimulator.Server.Factories;
using CarSimulator.Server.Models.ViewModels;
using DataLogicLibrary.Factories;
using DataLogicLibrary.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarSimulator.Server.Controllers
{
    public class CarSimulatorController : Controller
    {

        public CarSimulatorController(IAPIService apiService, ISimulationLogicService simulationLogicService, ICarFactory carFactory,
                                      IDriverFactory driverFactory, IStatusFactory statusFactory, IStatusMessageService statusMessageService)
        {
            _apiService = apiService;
            _simulationLogicService = simulationLogicService;
            _carFactory = carFactory;
            _driverFactory = driverFactory;
            _statusFactory = statusFactory;
            _statusMessageService = statusMessageService;
        }

        private readonly IAPIService _apiService;
        private readonly ISimulationLogicService _simulationLogicService;
        private readonly ICarFactory _carFactory;
        private readonly IDriverFactory _driverFactory;
        private readonly IStatusFactory _statusFactory;
        private readonly IStatusMessageService _statusMessageService;



        public async Task<IActionResult> Index(SimulationViewModel viewModel)
        {
            if (viewModel.SelectedAction == 7)
            {
                return RedirectToAction("Index");
            }

            if (viewModel.Driver == null)
            {
                var resultDTO = await _apiService.GetOneDriver();
                var driver = _driverFactory.CreateDriver(resultDTO);
                viewModel.Driver = driver;
            }

            if (viewModel.IsRunning)
            {
                if (viewModel.Car != null)
                {
                    viewModel.CurrentStatus = _simulationLogicService.DecreaseStatusValues(viewModel.SelectedAction, viewModel.CurrentStatus);
                    viewModel.CurrentStatus = _simulationLogicService.PerformAction(viewModel.SelectedAction, viewModel.CurrentStatus);
                }

                else
                {
                    viewModel.Car = _carFactory.CreateCar();
                    viewModel.CurrentStatus = _statusFactory.CreateStatus();
                }

                viewModel.CurrentActionMessage = _statusMessageService.GetCurrentActionMessage(viewModel.SelectedAction, viewModel.CurrentStatus.GasValue, viewModel.Driver.First)!;
                viewModel.DriverStatusMessage = _statusMessageService.GetDriverStatusMessage(viewModel.CurrentStatus.EnergyValue, viewModel.Driver.First)!;
                viewModel.CarStatusMessage = _statusMessageService.GetCarStatusMessage(viewModel.CurrentStatus.GasValue)!;
            }

            ModelState.Clear();
            return View(viewModel);
        }

    }
}

CarSimulator.Server/Views/CarSimulator/Index.cshtml
@{
    ViewData["Title"] = "Car Simulator";
}
@model SimulationViewModel

<div class="text-center">
    @if (!Model.IsRunning)
    {

        <h1 class="display-4">Car Simulator</h1>

        <div class="status-card">

            <p> Your Driver: @Model.Driver.Title. @Model.Driver.First @Model.Driver.Last </p>
            <p> City: @Model.Driver.City </p>
            <p> Country: @Model.Driver.Country</p>


            <p class="status-message">Do you want to start? </p>


        </div>

        <form asp-action="Index" method="post">
            <input type="hidden" asp-for="Driver.First" />
            <input type="hidden" asp-for="Driver.Last" />
            <input type="hidden" asp-for="IsRunning" value="true"/>
            <button type="submit" class="btn">Start Simulation</button>
        </form>


    }

    else
    {
        <div class="status-card">
            <h2>Status</h2>
            <ul>
                <li>Driver: @Model.Driver.First @Model.Driver.Last</li>
                <li>Direction: @Model.CurrentStatus.CardinalDirection</li>
                <li>Gas: @Model.CurrentStatus.GasValue</li>
                <li>Energy: @Model.CurrentStatus.EnergyValue</li>
            </ul>

            @if (Model.DriverStatusMessage != null || !string.IsNullOrEmpty(Model.DriverStatusMessage))
            {
                <p class="status-message-warning">
                    @Model.DriverStatusMessage
                    @if (Model.CurrentStatus.EnergyValue == 0)
                    {
                        <img src="../warning.png" alt="Warning" style="width:1em;vertical-align:middle;" />
                    }
                </p>

            }
            @if (Model.CarStatusMessage != null || !string.IsNullOrEmpty(Model.CarStatusMessage))
            {

                <p class="status-message-warning">
                    @Model.CarStatusMessage

                    @if (Model.CurrentStatus.GasValue == 0)
                    {
                        <img src="../warning.png" alt="Warning" style="width:1em;vertical-align:middle;" />
                    }
                </p>

            }
            <p class="status-message">@Model.CurrentActionMessage</p>
        </div>

        <div class="selection">

            <form asp-action="Index" method="post">
                <label for="SelectedAction">Select an action:</label>
                <select asp-for="SelectedAction" class="form-select" required>
                    <option value="">-- Choose an option --</option>
                    <option value="1">Turn left</option>
                    <option value="2">Turn right</option>
                    <option value="3">Drive forward</option>
                    <option value="4">Reverse</option>
                    <option value="5">Take a rest</option>
                    <option value="6">Refuel the car</option>
                    <option value="7">Exit</option>
                </select>
                <br />

                <input type="hidden" asp-for="Car.CardinalDirection" />
                <input type="hidden" asp-for="Car.GasValue" />
                <input type="hidden" asp-for="IsRunning" />
                <input type="hidden" asp-for="CurrentStatus.MovementAction" />
                <input type="hidden" asp-for="CurrentStatus.CardinalDirection" />
                <input type="hidden" asp-for="CurrentStatus.EnergyValue" />
                <input type="hidden" asp-for="CurrentStatus.GasValue" />
                <input type="hidden" asp-for="Driver.First" />
                <input type="hidden" asp-for="Driver.Last" />


                <button type="submit" class="btn btn-success">Submit</button>
            </form>
        </div>
    }

</div>

CarSimulator.Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] </title>
    <script type="importmap"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarSimulator.Server.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="CarSimulator" asp-action="Index">DevOps 25</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CarSimulator" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>